version: "3.8"

services:
  web:
    container_name: tasksapp
    restart: always
    build: .
    ports:
      - mongodb+srv://danielpoliakov:daniel.poliakov@cluster0.mhbc6.mongodb.net/test
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: tasksdb
    image: mongo
    ports:
      - "mongodb+srv://danielpoliakov:daniel.poliakov@cluster0.mhbc6.mongodb.net/test"
    logging:
      driver: none
